function [RH_cross_point] = biphasic_to_single_phase_RH_master_v1(O2C, Mratio)
%MYNEURALNETWORKFUNCTION neural network simulation function.
%
% Generated by Neural Network Toolbox function genFunction, 06-Apr-2018 13:11:25.
%
% [y1] = myNeuralNetworkFunction(x1) takes these arguments:
%   x = Qx3 matrix, input #1
% and returns:
%   y = Qx1 matrix, output #1
% where Q is the number of samples.

%#ok<*RPMT0>

%setup inputs
error(' use version 2')

    
    x1=[O2C, Mratio];

    
% RH_cross_point=biphasic_to_single_phase_RH_NN_v1(x1);
RH_cross_point=biphasic_to_single_phase_RH_NN_v3(x1);

[y1] = biphasic_to_single_phase_molfrac_org_NN_v4(x1)

  %round to zero
lower_round=RH_cross_point>0;
RH_cross_point=RH_cross_point.*lower_round+not(lower_round).*10^-10;
% round max to 1
upper_round=RH_cross_point>1;
RH_cross_point=not(upper_round).*RH_cross_point+upper_round;


end
